services:
  exporter_name:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - "2112:2112"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
